name: Generar y Publicar Javadoc

on:
  push:
    branches:
      - stable

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar Javadoc
        run: |
          # Usamos el comando que probamos antes
          javadoc -d docs -sourcepath src/main/java -subpackages com.tt1.test 
          
      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages 
